theme: jekyll-theme-minimal
title: Dear Tech Leader,
description: a love letter to Tech Leaders from their CEOs/CFOs
logo: /images/dear-auditor-logo.png
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
